In [1]:
#Import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
#import file for task
ds=pd.read_csv("raw_messy_dataset.csv")
ds

Name      Age Gender              Email     Join_Date Salary  \
0      Alice      NaN    NaN  user0@example.com    2021-05-21    NaN   
1        Bob       40      M  user1@example.com           NaN  50000   
2    Charlie  unknown   Male  user2@example.com    2020/01/01  50000   
3      David      NaN    NaN  user3@example.com    2021-05-21  70000   
4        Eva       35  Other  user4@example.com  July 4, 2020  70000   
..       ...      ...    ...                ...           ...    ...   
100    Alice      NaN    NaN  user0@example.com    2021-05-21    NaN   
101      Bob       40      M  user1@example.com           NaN  50000   
102  Charlie  unknown   Male  user2@example.com    2020/01/01  50000   
103    David      NaN    NaN  user3@example.com    2021-05-21  70000   
104      Eva       35  Other  user4@example.com  July 4, 2020  70000   

      Department  
0          Admin  
1    Engineering  
2             HR  
3          Admin  
4    Engineering  
..           ...  
100        Admin  
101  Engineering  
102           HR  
103        Admin  
104  Engineering  

[105 rows x 7 columns]

In [6]:
#Display first 10 observations

ds.head(10)

Name      Age  Gender              Email     Join_Date Salary  \
0    Alice      NaN     NaN  user0@example.com    2021-05-21    NaN   
1      Bob       40       M  user1@example.com           NaN  50000   
2  Charlie  unknown    Male  user2@example.com    2020/01/01  50000   
3    David      NaN     NaN  user3@example.com    2021-05-21  70000   
4      Eva       35   Other  user4@example.com  July 4, 2020  70000   
5    Frank  unknown   Other  user5@example.com           NaN  70000   
6    Grace  unknown  Female  user6@example.com  July 4, 2020  80000   
7   Hannah      NaN   Other  user7@example.com    2021-05-21    NaN   
8      Ivy       30  Female  user8@example.com           NaN  50000   
9     Jack       35    Male  user9@example.com    2020/01/01  80000   

    Department  
0        Admin  
1  Engineering  
2           HR  
3        Admin  
4  Engineering  
5        Admin  
6  Engineering  
7           HR  
8  Engineering  
9  Engineering

In [7]:
#Check all information of data
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Name        105 non-null    object
 1   Age         72 non-null     object
 2   Gender      89 non-null     object
 3   Email       95 non-null     object
 4   Join_Date   70 non-null     object
 5   Salary      78 non-null     object
 6   Department  89 non-null     object
dtypes: object(7)
memory usage: 5.9+ KB


In [8]:
#To describe data
ds.describe()

Name Age Gender              Email   Join_Date Salary   Department
count     105  72     89                 95          70     78           89
unique     10   5      5                 90           4      5            5
top     Alice  40   Male  user0@example.com  2021-05-21  50000  Engineering
freq       11  22     22                  2          26     22           26

In [15]:
#Searching for duplicates
ds.duplicated()
#or
ds.duplicated().sum()

np.int64(0)

In [14]:
#Remove Duplicates
ds.drop_duplicates(inplace=True)

In [16]:
#To get columns only
ds.columns

Index(['Name', 'Age', 'Gender', 'Email', 'Join_Date', 'Salary', 'Department'], dtype='object')

# Handling Age

In [25]:
#conver it into numberic form
ds["Age"]=pd.to_numeric(ds["Age"],errors='coerce')
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Name        100 non-null    object 
 1   Age         100 non-null    float64
 2   Gender      86 non-null     object 
 3   Email       90 non-null     object 
 4   Join_Date   66 non-null     object 
 5   Salary      74 non-null     object 
 6   Department  84 non-null     object 
dtypes: float64(1), object(6)
memory usage: 6.2+ KB


In [30]:
#To check age has unique value have or not
ds["Age"].unique()

array([35., 40., 30., 25.])

In [29]:
#To fill data in column age
x=ds["Age"].median()
ds["Age"].fillna(x,inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_24272\2011051617.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ds["Age"].fillna(x,inplace=True)


# Handling Gender

In [31]:
#To check unique values
ds["Gender"].unique()

array([nan, 'M', 'Male', 'Other', 'Female', 'F'], dtype=object)

In [32]:
#To replace 'M','F'with 'Male','female'
ds["Gender"]=ds["Gender"].replace({
    "M" : "Male","F" : "Female"," " : "None"
})
ds["Gender"].unique()

array([nan, 'Male', 'Other', 'Female'], dtype=object)

In [57]:
# Fill No where email not present
ds["Gender"].fillna("No",inplace=True)
ds["Gender"].unique()

array(['No', 'Male', 'Other', 'Female'], dtype=object)

# Handling Email

In [37]:
#fill email as Nan and other
ds["Email"].fillna("-",inplace=True)
ds

Name   Age  Gender              Email     Join_Date Salary   Department
0     Alice  35.0     NaN  user0@example.com    2021-05-21    NaN        Admin
1       Bob  40.0    Male  user1@example.com           NaN  50000  Engineering
2   Charlie  35.0    Male  user2@example.com    2020/01/01  50000           HR
3     David  35.0     NaN  user3@example.com    2021-05-21  70000        Admin
4       Eva  35.0   Other  user4@example.com  July 4, 2020  70000  Engineering
..      ...   ...     ...                ...           ...    ...          ...
95    Frank  35.0    Male                  -           NaN  50000          NaN
96    Grace  40.0    Male                  -           NaN  70000        Sales
97   Hannah  35.0    Male                  -    2020/01/01  60000          NaN
98      Ivy  35.0  Female                  -    2020/01/01  50000          NaN
99     Jack  35.0     NaN                  -  July 4, 2020  60000        Admin

[100 rows x 7 columns]

# handling Date-Time

In [38]:
#To check the date is in which format
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Name        100 non-null    object 
 1   Age         100 non-null    float64
 2   Gender      86 non-null     object 
 3   Email       100 non-null    object 
 4   Join_Date   66 non-null     object 
 5   Salary      74 non-null     object 
 6   Department  84 non-null     object 
dtypes: float64(1), object(6)
memory usage: 6.2+ KB


In [39]:
#To convert Date in date-time format
ds["Join_Date"]=pd.to_datetime(ds["Join_Date"],errors='coerce')
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   Name        100 non-null    object        
 1   Age         100 non-null    float64       
 2   Gender      86 non-null     object        
 3   Email       100 non-null    object        
 4   Join_Date   24 non-null     datetime64[ns]
 5   Salary      74 non-null     object        
 6   Department  84 non-null     object        
dtypes: datetime64[ns](1), float64(1), object(5)
memory usage: 6.2+ KB


In [52]:
# To fill null in where date time not present
ds["Join_Date"].fillna("Null",inplace=True)
ds["Join_Date"].unique()

array([Timestamp('2021-05-21 00:00:00'), 'Null'], dtype=object)

# Handling salary

In [41]:
#To convert salary  in nummeric form
ds["Salary"]=pd.to_numeric(ds["Salary"],errors='coerce')
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   Name        100 non-null    object        
 1   Age         100 non-null    float64       
 2   Gender      86 non-null     object        
 3   Email       100 non-null    object        
 4   Join_Date   24 non-null     datetime64[ns]
 5   Salary      60 non-null     float64       
 6   Department  84 non-null     object        
dtypes: datetime64[ns](1), float64(2), object(4)
memory usage: 6.2+ KB


# Handling department

In [42]:
#Fill null in blanck spaces
y=ds["Department"].mode()[0]
ds["Department"].fillna(y,inplace=True)
ds["Department"].unique()

C:\Users\hp\AppData\Local\Temp\ipykernel_24272\3794904978.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ds["Department"].fillna(y,inplace=True)


array(['Admin', 'Engineering', 'HR', 'Sales', 'Marketing'], dtype=object)

In [58]:
ds.to_csv("Cleaned data.csv")